server:
  port: 8083
spring:
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 39.106.141.135:9300
  rabbitmq:
    host: 39.106.141.135
    virtual-host: /leyou
    username: leyou
    password: ******
  jackson:
    default-property-inclusion: non_null  # 过滤为null的响应结果
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期

