server:
  port: 8084
spring:
  application:
    name: goods-web
  # 开发的时候关闭掉缓存
  thymeleaf:
    cache: false
  rabbitmq:
    host: 39.106.141.135
    virtual-host: /leyou
    username: leyou
    password: lq299199
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
