server:
  port: 10010
spring:
  application:
    name: leyou-gateway
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /api # 路由路径前缀
  retryable: true  # 开启重试
  routes:
    item-service: /item/**  # 路由到商品的微服务
    search-service: /search/** # 路由到搜索微服务
    user-service: /user/**  # 路由到用户微服务
    auth-service: /auth/**  # 路由到授权中心微服务
    cart-service: /cart/**  # 到购物车

  add-host-header: true  # 携带请求本身的头信息
  sensitive-headers:   # 覆盖敏感头信息 不然拿不到set-cookie
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 5000 # 熔断超时时长：5000ms
leyou:
  jwt:
    pubKeyPath: D:\\study\\java\\projects\\tmp\\rsa\\rsa.pub # 公钥地址
    cookieName: LY_TOKEN # cookie的名称
  filter:
    allowPaths:  # 过滤白名单 List<String> allowPaths
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item